jobs:
  build:
    runs-on: depot-ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build and push Docker image
        uses: depot/build-push-action@v1
        with:
          push: true
          tags: user/app:latest
